name: ssl2
channels:
  - anaconda
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - imageio>=2.13
  - pandas
  - plotly
  - pip
  - pytorch=1.13
  - pytorch-cuda=11.7
  - tensorboard
  - tensorboardx
  - torchvision
  - pip:
    - accelerate
    - hydra-core
    - omegaconf
    - pyyaml
    - tqdm
    - wandb
    - kornia>=0.6.9
