defaults:
  - evaluator: std
  - _self_

set: test
batch_size: 512
track_best: off
use_ema_metrics: off
use_ema_weights: on
patience_epochs: null
size: .1
epoch_interval: 1
keep_all: off
keep_all_best: off
