defaults:
  - evaluator: std
  - _self_

set: val
batch_size: 512
track_best: on
use_ema_metrics: off
use_ema_weights: on
patience_epochs: null
size: .1
epoch_interval: 10
keep_all: off
keep_all_best: off
