defaults:
  - optimizer: sgd
  - lr_scheduler: cosine
  - _self_

null_target: ${dataset.null_target}
num_epochs: 1000
batch_size: 64
bs_unlabeled_factor: null
freeze_bn: false
ema_decay: 0.999
optimizer:
  lr: 3e-2
  momentum: .9
  nesterov: True
  weight_decay: 1.e-3
